/**
 * @file
 * @brief Uniform distribution on the real line.
 */

#ifndef SIMPLEMC_RANDOM_UNIFORM_REAL_DISTRIBUTION_HPP
#define SIMPLEMC_RANDOM_UNIFORM_REAL_DISTRIBUTION_HPP

#include <simplemc/random/generate_uniform_real.hpp>
#include <simplemc/utils/simplemc_exception.hpp>

#include <cassert>
#include <iostream>
#include <limits>

namespace simplemc {

/**
 * @ingroup simplemc-random-dists
 * @brief Uniform real distribution on an interval of the real line.
 *
 * @details Only to be used with 64-bit RNGs.
 *
 * It satisfies the C++ named requirements: <a href="https://en.cppreference.com/w/cpp/named_req/
 * RandomNumberDistribution">RandomNumberDistribution</a> and is an alternative to
 * `std::uniform_real_distribution<double>`.
 *
 * Floating-point number generation is taken from http://prng.di.unimi.it/ and it is intended to be
 * used with simplemc::xoshrio256 generators (although any other 64-bit engine works as well if it
 * generates `std::uint64_t` numbers).
 */
class uniform_real_distribution {
public:
    /**
     * @brief Type of the random number generated.
     */
    using result_type = double;

    /**
     * @brief Parameter type of a simplemc::uniform_real_distribution.
     *
     * @details It models an closed-open interval on the real line and defines the domain of the
     * distribution.
     */
    class param_type {
    public:
        /**
         * @brief Type of distribution to which the parameter type belongs.
         */
        using distribution_type = uniform_real_distribution;

        /**
         * @brief Construct distribution parameters by specifying the lower and upper bound of the
         * interval.
         *
         * @param min_arg Lower bound of the interval.
         * @param max_arg Upper bound of the interval.
         */
        explicit param_type(double min_arg = 0.0, double max_arg = 1.0) : min_(min_arg), max_(max_arg) {
            assert(min_ < max_);
        }

        /**
         * @brief Get lower bound of the interval.
         *
         * @return Minimum value generated by the corresponding simplemc::uniform_real_distribution.
         */
        [[nodiscard]] double min() const { return min_; }

        /**
         * @brief Get upper bound of the interval.
         *
         * @return Maximum value generated by the corresponding simplemc::uniform_real_distribution.
         */
        [[nodiscard]] double max() const { return max_; }

        /**
         * @brief Compare two simplemc::uniform_real_distribution::param_type obejcts for equality.
         *
         * @param lhs Left-hand side distribution parameters.
         * @param rhs Right-hand side distribution parameters.
         * @return True if they represent the same interval/domain.
         */
        [[nodiscard]] friend bool operator==(const param_type& lhs, const param_type& rhs) {
            return (lhs.min() == rhs.min() && lhs.max() == rhs.max());
        }

        /**
         * @brief Compare two simplemc::uniform_real_distribution::param_type objects for inequality.
         *
         * @param lhs Left-hand side distribution parameters.
         * @param rhs Right-hand side distribution parameters.
         * @return True if they represent distinct intervals/domains.
         */
        [[nodiscard]] friend bool operator!=(const param_type& lhs, const param_type& rhs) { return !(lhs == rhs); }

    private:
        double min_;
        double max_;
    };

    /**
     * @brief Construct a distribution on the interval `[min_arg, max_arg)`.
     *
     * @param min_arg Lower bound of the interval.
     * @param max_arg Upper bound of the interval.
     */
    explicit uniform_real_distribution(double min_arg = 0.0, double max_arg = 1.0) : param_(min_arg, max_arg) {}

    /**
     * @brief Construct a distribution from given distribution parameters.
     *
     * @param param Parameters specifying the domain of the distribution.
     */
    explicit uniform_real_distribution(const param_type& param) : param_(param) {}

    /**
     * @brief Lower bound of the interval.
     *
     * @return Minimum value generated by the distribution.
     */
    [[nodiscard]] double min() const { return param_.min(); }

    /**
     * @brief Upper bound of the interval.
     *
     * @return Maximum value generated by the distribution.
     */
    [[nodiscard]] double max() const { return param_.max(); }

    /**
     * @brief Get the distribution parameters, i.e. the domain on which the distribution is defined.
     *
     * @return Distribution parameters.
     */
    [[nodiscard]] param_type param() const { return param_; }

    /**
     * @brief Set the distribution parameters, i.e. the domain on which the distribution is defined.
     *
     * @param param Distribution parameters.
     */
    void param(const param_type& param) { param_ = param; }

    /**
     * @brief Reset the internal state of distribution.
     */
    void reset() {}

    /**
     * @brief Generate a uniform real random number.
     *
     * @note The given RNG is assumed to produce 64-bit unsigned integers.
     *
     * @tparam RNG 64-bit Random number generator type.
     * @param rng RNG object.
     * @return Random double on the domain of the distribution.
     */
    template <typename RNG>
    double operator()(RNG& rng) const {
        return detail::generate_uniform_real(rng, param_.min(), param_.max());
    }

    /**
     * @brief Generate a uniform real random number according to the given distribution parameters.
     *
     * @note The given RNG is assumed to prduce 64-bit unsigned integers.
     *
     * @tparam RNG 64-bit Random number generator type.
     * @param rng RNG object.
     * @param param Disribution parameters specifying the domain of the distribution.
     * @return Random double on the domain according to the given distribution parameters.
     */
    template <typename RNG>
    double operator()(RNG& rng, const param_type& param) const {
        return detail::generate_uniform_real(rng, param.min(), param.max());
    }

    /**
     * @brief Compare two simplemc::uniform_real_distribution objects for equality.
     *
     * @param lhs Left-hand side distribution.
     * @param rhs Right-hand side distribution.
     * @return True if the parameters of the distributions are the same.
     */
    [[nodiscard]] friend bool operator==(const uniform_real_distribution& lhs, const uniform_real_distribution& rhs) {
        return (lhs.param() == rhs.param());
    }
    /**
     * @brief Compare two simplemc::uniform_real_distribution objects for inequality.
     *
     * @param lhs Left-hand side distribution.
     * @param rhs Right-hand side distribution.
     * @return True if the parameters of the distributions are distinct.
     */
    [[nodiscard]] friend bool operator!=(const uniform_real_distribution& lhs, const uniform_real_distribution& rhs) {
        return !(lhs == rhs);
    }

    /**
     * @brief Write a textual representation of a simplemc::uniform_real_distribution object to
     * `std::ostream`.
     *
     * @details Throws an exception, if writing `to std::ostream` fails.
     *
     * @param os `std::ostream` to write to.
     * @param ud Distribution to be written.
     * @return Reference to the `std::ostream` object.
     */
    friend std::ostream& operator<<(std::ostream& os, const uniform_real_distribution& ud) {
        auto prec = os.precision();
        os.precision(std::numeric_limits<double>::max_digits10);
        if (!(os << ud.param().min() << ' ' << ud.param().max())) {
            throw simplemc_exception("Error writing a simplemc::uniform_real_distribution to ostream");
        }
        os.precision(prec);
        return os;
    }

    /**
     * @brief Read a textual representations of a simplemc::uniform_real_distribution object from
     * `std::istream`.
     *
     * @details Throws an exception, if reading from `std::istream` fails.
     *
     * @param is `std::istream` to read from.
     * @param ud Distribution to be read into.
     * @return Reference to the `std::istream` object.
     */
    friend std::istream& operator>>(std::istream& is, uniform_real_distribution& ud) {
        double min = 0, max = 0;
        if (is >> min >> std::ws >> max) {
            if (min < max) {
                ud.param(uniform_real_distribution::param_type { min, max });
            } else {
                is.setstate(std::ios_base::failbit);
            }
        } else {
            throw simplemc_exception("Error reading a simplemc::uniform_real_distribution from istream");
        }
        return is;
    }

private:
    param_type param_;
};

} // namespace simplemc

#endif // SIMPLEMC_RANDOM_UNIFORM_REAL_DISTRIBUTION_HPP
