/**
 * @file uniform_real_distribution.hpp
 * @brief Uniform distribution on the real line.
 */

#ifndef SIMPLEMC_RANDOM_UNIFORM_REAL_DISTRIBUTION_HPP
#define SIMPLEMC_RANDOM_UNIFORM_REAL_DISTRIBUTION_HPP

#include <simplemc/random/generate_uniform_real.hpp>

#include <iosfwd>

namespace simplemc {

/* Forward declarations. */
class uniform_real_distribution;

namespace detail {

/**
 * @brief Parameter type of the simplemc::uniform_real_distribution.
 *
 * @details Models an interval [min, max).
 */
class urd_param_type {
public:
    /**
     * @brief Type of distribution.
     */
    using distribution_type = uniform_real_distribution;

    /**
     * @brief Construct distribution parameters with values for [min, max).
     *
     * @param min_arg Lower bound.
     * @param max_arg Upper bound.
     */
    explicit urd_param_type(double min_arg = 0.0, double max_arg = 1.0);

    /**
     * @brief Get lower bound of [min, max).
     *
     * @return Minimum value generated by the distribution.
     */
    [[nodiscard]] double min() const { return min_; }

    /**
     * @brief Get upper bound of [min, max).
     *
     * @return Maximum value generated by the distribution.
     */
    [[nodiscard]] double max() const { return max_; }

private:
    double min_;
    double max_;
};

/**
 * @brief Write a textual representation of distribution parameters to std::ostream.
 *
 * @details Throws an exception, if writing to std::ostream fails.
 *
 * @param os std::ostream to write to.
 * @param param Distribution parameters to be written.
 * @return Reference to the std::ostream object.
 */
std::ostream& operator<<(std::ostream& os, const urd_param_type& param);

/**
 * @brief Read a textual representation of distribution parameters from std::istream.
 *
 * @details Throws an exception, if reading from std::istream fails.
 *
 * @param is std::istream to read from.
 * @param param Distribution parameters to read into.
 * @return Reference to the std::istream object.
 */
std::istream& operator>>(std::istream& is, urd_param_type& param);

/**
 * @brief Compare two distribution parameters for equality.
 *
 * @param lhs Left-hand side distribution parameters.
 * @param rhs Right-hand side distribution parameters.
 * @return True if they represent the same interval.
 */
[[nodiscard]] bool operator==(const urd_param_type& lhs, const urd_param_type& rhs);

/**
 * @brief Compare two distribution parameters for inequality.
 *
 * @param lhs Left-hand side distribution parameters.
 * @param rhs Right-hand side distribution parameters.
 * @return True if they represent distinct intervals.
 */
[[nodiscard]] bool operator!=(const urd_param_type& lhs, const urd_param_type& rhs);

} // namespace detail

/**
 * @brief Uniform real distribution on the interval [min, max).
 *
 * @details Only to be used with 64-bit RNGs. Satisfies the requirements for a C++
 * RandomNumberDistribution and is similar to boost::random::uniform_real_distribution<double>
 * or std::uniform_real_distribution<double>. The major difference is how floating-point numbers
 * are generated. Floating-point number generation is taken from http://prng.di.unimi.it/ and it
 * is intended to be used with xoshrio256 generators (although any other 64-bit engine can be
 * used as well if it generates std::uint64_t numbers).
 *
 * On each vocation it generates a random double uniformly distributed between [min, max).
 */
class uniform_real_distribution {
public:
    /**
     * @brief Type of the random number generated.
     */
    using result_type = double;

    /**
     * @brief Parameter type of the distribution.
     */
    using param_type = detail::urd_param_type;

    /**
     * @brief Construct a distribution on the interval [min, max).
     *
     * @param min_arg Lower bound.
     * @param max_arg Upper bound.
     */
    explicit uniform_real_distribution(double min_arg = 0.0, double max_arg = 1.0);

    /**
     * @brief Construct a distribution from given distribution parameters.
     *
     * @param param Parameters specifying [min, max).
     */
    explicit uniform_real_distribution(const param_type& param);

    /**
     * @brief Lower bound of [min, max).
     *
     * @return Minimum value generated by the distribution.
     */
    [[nodiscard]] double min() const { return param_.min(); }

    /**
     * @brief Upper bound of [min, max).
     *
     * @return Maximum value generated by the distribution.
     */
    [[nodiscard]] double max() const { return param_.max(); }

    /**
     * @brief Get the distribution parameters, i.e. the interval on which the distribution is defined.
     *
     * @return Distribution parameters.
     */
    [[nodiscard]] param_type param() const { return param_; }

    /**
     * @brief Set the distribution parameters, i.e. the interval on which the distribution is defined.
     *
     * @param param Distribution parameters.
     */
    void param(const param_type& param) { param_ = param; }

    /**
     * @brief Reset internal state of distribution.
     */
    void reset() {}

    /**
     * @brief Generate a uniform real random number.
     *
     * @details The RNG has to produce 64-bit values.
     *
     * @tparam RNG 64-bit Random number generator.
     * @param rng RNG object.
     * @return Random double on the current interval [min, max).
     */
    template <typename RNG>
    double operator()(RNG& rng) const {
        return detail::generate_uniform_real(rng, param_.min(), param_.max());
    }

    /**
     * @brief Generate a uniform real random number according to the given distribution parameters.
     *
     * @tparam RNG 64-bit Random number generator.
     * @param rng RNG object.
     * @param param Disribution parameters.
     * @return Random double distributed according to the given distribution parameters.
     */
    template <typename RNG>
    double operator()(RNG& rng, const param_type& param) const {
        return detail::generate_uniform_real(rng, param.min(), param.max());
    }

private:
    param_type param_;
};

/**
 * @brief Write a textual representation of a distribution to std::ostream.
 *
 * @details Throws an exception, if writing to std::ostream fails.
 *
 * @param os std::ostream to write to.
 * @param ud Distribution to be written.
 * @return Reference to the std::ostream object.
 */
std::ostream& operator<<(std::ostream& os, const uniform_real_distribution& ud);

/**
 * @brief Read a textual representations of a distribution from std::istream.
 *
 * @details Throws an exception, if reading from std::istream fails.
 *
 * @param is std::istream to read from.
 * @param ud Distribution to be read into.
 * @return Reference to the std::istream object.
 */
std::istream& operator>>(std::istream& is, uniform_real_distribution& ud);

/**
 * @brief Compare two distributions for equality.
 *
 * @param lhs Left-hand side distribution.
 * @param rhs Right-hand side distribution.
 * @return True if the parameters of the distributions are the same.
 */
[[nodiscard]] bool operator==(const uniform_real_distribution& lhs, const uniform_real_distribution& rhs);

/**
 * @brief Compare two distributions for inequality.
 *
 * @param lhs Left-hand side distribution.
 * @param rhs Right-hand side distribution.
 * @return True if the parameters of the distributions are distinct.
 */
[[nodiscard]] bool operator!=(const uniform_real_distribution& lhs, const uniform_real_distribution& rhs);

} // namespace simplemc

#endif // SIMPLEMC_RANDOM_UNIFORM_REAL_DISTRIBUTION_HPP
