/**
 * @file uniform_real_distribution.hpp
 * @brief Uniform distribution on the real line.
 */

#ifndef SIMPLEMC_RANDOM_UNIFORM_REAL_DISTRIBUTION_HPP
#define SIMPLEMC_RANDOM_UNIFORM_REAL_DISTRIBUTION_HPP

#include <simplemc/random/generate_uniform_real.hpp>

#include <iosfwd>

namespace simplemc {

/* Forward declarations. */
class uniform_real_distribution;

namespace detail {

/**
 * @brief Parameter type of the simplemc::uniform_real_distribution.
 *
 * @details Models an interval [min, max).
 */
class urd_param_type {
public:
    /**
     * @brief Type of distribution.
     */
    using distribution_type = uniform_real_distribution;

    /**
     * @brief Construct a urd_param_type with values for [min, max).
     *
     * @param min_arg Lower bound.
     * @param max_arg Upper bound.
     */
    explicit urd_param_type(double min_arg = 0.0, double max_arg = 1.0);

    /**
     * @brief Get lower bound of [min, max).
     *
     * @return Minimum value generated by the distribution.
     */
    [[nodiscard]] double min() const { return min_; }

    /**
     * @brief Get upper bound of [min, max).
     *
     * @return Maximum value generated by the distribution.
     */
    [[nodiscard]] double max() const { return max_; }

private:
    double min_;
    double max_;
};

/**
 * @brief Write textual representation of urd_param_type to ostream.
 *
 * @details Throws an exception, if writing to ostream fails.
 *
 * @param os std::ostream.
 * @param param Parameters.
 * @return Reference to the std::ostream object.
 */
std::ostream& operator<<(std::ostream& os, const urd_param_type& param);

/**
 * @brief Read textual representation of urd_param_type from istream.
 *
 * @details Throws an exception, if reading from istream fails.
 *
 * @param is std::istream.
 * @param param Parameters.
 * @return Reference to the std::istream object.
 */
std::istream& operator>>(std::istream& is, urd_param_type& param);

/**
 * @brief Compare two urd_param_type objects for equality.
 *
 * @param lhs Parameters #1.
 * @param rhs Parameters #2.
 * @return `true` if both their `min_` and `max_` values are equal.
 */
[[nodiscard]] bool operator==(const urd_param_type& lhs, const urd_param_type& rhs);

/**
 * @brief Compare two urd_param_type objects for inequality.
 *
 * @param lhs Parameters #1.
 * @param rhs Parameters #2.
 * @return `true` if either their `min_` or `max_` values are not equal.
 */
[[nodiscard]] bool operator!=(const urd_param_type& lhs, const urd_param_type& rhs);

} // namespace detail

/**
 * @brief Uniform real distribution on the interval [min, max).
 *
 * @details Only to be used with 64-bit RNGs. Satisfies the requirements for a C++
 * RandomNumberDistribution and is similar to boost::random::uniform_real_distribution<double>
 * or std::uniform_real_distribution<double>. The major difference is how floating-point numbers
 * are generated. Floating-point number generation is taken from http://prng.di.unimi.it/ and it
 * is intended to be used with xoshrio256 generators (although any other 64-bit engine can be
 * used as well if it generates std::uint64_t numbers).
 *
 * On each vocation it generates a random double uniformly distributed between [min, max).
 */
class uniform_real_distribution {
public:
    /**
     * @brief Type of the random number generated.
     */
    using result_type = double;

    /**
     * @brief Parameter type of the distribution.
     */
    using param_type = detail::urd_param_type;

    /**
     * @brief Construct a uniform_real_distribution on the interval [min_arg, max_arg).
     *
     * @param min_arg Lower bound.
     * @param max_arg Upper bound.
     */
    explicit uniform_real_distribution(double min_arg = 0.0, double max_arg = 1.0);

    /**
     * @brief Construct a uniform_real_distribution from a given param_type.
     *
     * @param param Parameter specifying [min, max).
     */
    explicit uniform_real_distribution(const param_type& param);

    /**
     * @brief Lower bound of [min, max).
     *
     * @return Minimum value generated by the distribution.
     */
    [[nodiscard]] double min() const { return param_.min(); }

    /**
     * @brief Upper bound of [min, max).
     *
     * @return Maximum value generated by the distribution.
     */
    [[nodiscard]] double max() const { return param_.max(); }

    /**
     * @brief Get interval [min, max) as a param_type object.
     *
     * @return Interval on which the current distribution is defined.
     */
    [[nodiscard]] param_type param() const { return param_; }

    /**
     * @brief Set interval [min, max) on which the distribution is defined.
     *
     * @param param New bounds for the distribution.
     */
    void param(const param_type& param) { param_ = param; }

    /**
     * @brief Reset internal state of distribution.
     */
    void reset() {}

    /**
     * @brief Generate random number.
     *
     * @details The RNG has to produce 64-bit values.
     *
     * @tparam RNG 64-bit Random number generator.
     * @param rng RNG object.
     * @return Random double on the current interval [min, max).
     */
    template <typename RNG>
    double operator()(RNG& rng) const {
        return detail::generate_uniform_real(rng, param_.min(), param_.max());
    }

    /**
     * @brief Generate random number on the interval specified by param.
     *
     * @tparam RNG 64-bit Random number generator.
     * @param rng RNG object.
     * @param param Interval bounds.
     * @return Random double on the specified interval.
     */
    template <typename RNG>
    double operator()(RNG& rng, const param_type& param) const {
        return detail::generate_uniform_real(rng, param.min(), param.max());
    }

private:
    param_type param_;
};

/**
 * @brief Write a textual representation of a uniform_real_distribution to ostream.
 *
 * @details Throws an exception, if writing to ostream fails.
 *
 * @param os Reference to ostream.
 * @param ud Distribution to be written.
 * @return Reference to ostream.
 */
std::ostream& operator<<(std::ostream& os, const uniform_real_distribution& ud);

/**
 * @brief Restore uniform_real_distribution from istream.
 *
 * @details If reading from istream fails, the state is left unchanged and an exception is thrown.
 *
 * @param is Reference to istream.
 * @param ud Distribution to be read into.
 * @return Reference to istream.
 */
std::istream& operator>>(std::istream& is, uniform_real_distribution& ud);

/**
 * @brief Compare two uniform_real_distributions for equality.
 *
 * @param lhs Distribution #1.
 * @param rhs Distribution #2.
 * @return `true` if the parameters of the distributions are the same.
 */
[[nodiscard]] bool operator==(const uniform_real_distribution& lhs, const uniform_real_distribution& rhs);

/**
 * @brief Compare two uniform_real_distributions for inequality.
 *
 * @param lhs Distribution #1.
 * @param rhs Distribution #2.
 * @return `true` if the parameters of the distributions are distinct.
 */
[[nodiscard]] bool operator!=(const uniform_real_distribution& lhs, const uniform_real_distribution& rhs);

} // namespace simplemc

#endif // SIMPLEMC_RANDOM_UNIFORM_REAL_DISTRIBUTION_HPP
